name: Unit tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  NODE_VERSION: 16.x
  NEXT_ENV_VARS_HERE: ${{ secrets.NEXT_ENV_VARS_HERE }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test on Node version - ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install latest npm
        run: |
          npm install -g npm &&
          npm --version &&
          npm list -g --depth 0
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Headless tests
        run: npm run test:unit
